algoritmo "creusa"

var
   n: Real

inicio
      escreva ("Digite uma distancia em metros ")
              leia (n)
      escreval ("A distancia", n, "m", " conresponde a:")
      escreval ((n*0.001), " Km                           ", (n*10):8:1, " dm")
      escreval ((n*0.01), " Hm                            ", (n*100):8:1, " Cm")
      escreval ((n*0.1), " Dam                            ", (n*1000):8:1, " mm")
      
              

fimalgoritmo
